services:
  - type: web
    name: grocery-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: ./start.sh
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGHOST
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGPORT
        sync: false
      - key: PGUSER
        sync: false
      - key: NODE_ENV
        value: production